name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Instalamos Flutter (forzamos una versión 3 para evitar problemas de compatibilidad)
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' 

      # 2. Descargamos las librerías de tu pubspec.yaml
      - name: Install dependencies
        run: flutter pub get

      # 3. Compilamos para Web (Sin el parámetro problemático)
      - name: Build Web
        run: flutter build web --release --base-href "/axol-inventarios/"

      # 4. Desplegamos la carpeta compilada a la rama gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
